### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by streeck** [philchalmers/mirt#106]
There are several broken links in [mirt](https://philchalmers.github.io/mirt/html/mirt.html) docs under the `See Also` section.

Most of the links are pointing towards: `https://philchalmers.github.io/mirtbeta/*` while they should be pointing to: `https://philchalmers.github.io/mirt/*`

**Comment by philchalmers** [comment]
Thanks for noticing this; must have been a sloppy merge sometime back with my hidden dev version. I'll patch it next chance I get. Cheers.

**Comment by philchalmers** [comment]
Should be fixed now.

**Comment by streeck** [comment]
Nice, thanks.

On the same page though, the following link is still broken:
https://philchalmers.github.io/nlme/html/fixed.effects.html

**Comment by philchalmers** [comment]
That one is harder to change, because its not pointed to internally. I think it's more a problem with `knitr` than `mirt` because of how the docs are generated.
